services:
  # PostgreSQL Database
  postgres:
    image: postgres:17.5-alpine
    container_name: fastapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_starter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # FastAPI Application
  app:
    build: .
    container_name: fastapi-app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app

  # PgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:9.3
    container_name: fastapi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
