"""Add pending_verification_token to users table

Revision ID: ac6e6e84ac44
Revises: 7a210586a798
Create Date: 2025-05-25 15:05:14.541171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW - for SQLModel support


# revision identifiers, used by Alembic.
revision: str = 'ac6e6e84ac44'
down_revision: Union[str, None] = '7a210586a798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_verification_token')
    # ### end Alembic commands ###
